### ISSUE TITLE
memmap doesn't support an execute-only mapping.

### ISSUE THREAD

**Issue by Olsonist** [danburkert/memmap-rs#29]
memmap doesn't support an execute-only mapping.

In particular, this is useful for JITs where the usage scenario is:

- allocate/mmap a buffer as ReadWrite
- write instructions into it
- then mark/mprotect the pages as execute only (Execute).

An article by Eli Bendersky: [How to JIT - an introduction](http://eli.thegreenplace.net/2013/11/05/how-to-jit-an-introduction)

**Comment by danburkert** [comment]
Note that `memmap` doesn't provide an `mprotect` wrapper.  I'm not sure if one exists in the ecosystem already.  If not, it probably would be a nice addition to the library.

**Comment by Olsonist** [comment]
Yeah, you need mprotect because the usage scenario is alloc/write/mprotect.
And luckily, [mprotect is supported](https://doc.rust-lang.org/1.0.0/libc/funcs/posix88/mman/fn.mprotect.html) (which probably solves my _immediate_ problem which is nice).

So I might have solved my problem without changing memmap. Sorry for the thinking out loud.

**Comment by danburkert** [comment]
This API is present in master (`Mmap::set_protection`), as well as in the refactor in #46 (`MmapMut::make_exec`).
