### ISSUE TITLE
Support discontinuous memory maps

### ISSUE THREAD

**Issue by willglynn** [danburkert/memmap-rs#30]
I'm working with a file format that scatters its data around on disk. It's composed of multiple logical data streams which are intended to be memory mapped. The segments are all page-aligned, and records within a stream constantly refer to other records based on their positions within the stream entirely oblivious to the physical layout.

Ultimately I want a single continuous read-only `&[u8]` given a list of offsets and sizes:

    0x462C000:   0x1000 bytes
    0x473D000: 0x8C4000 bytes
    0x5003000: 0xFFE000 bytes
    0x6003000: 0x29E000 bytes

In the case of POSIX `mmap()`, I think this would be done by using `mmap(NULL, <total size>, MAP_ANON, PROT_NONE, 0, 0)` to ask for a chunk of address space without actually committing resources to it, followed by repeated `mmap(<address>, <size>, MAP_FIXED, PROT_READ, <fd>, <offset>)` to map each file piece to the appropriate location within that space.

On Windows, I think this is `VirtualAllocEx(MEM_RESERVE)` to get the address space, then `MapViewOfFileEx()` to map each piece.

**Comment by m4b** [comment]
Here's how a unix dynamic linker might do this: https://github.com/m4b/dryad/blob/585189f3986c284aad52701d6de944a06192ab01/src/loader.rs#L47-L70

E.g., the program headers need to be mmap'd  into different locations, but the code + data reference each other assuming it's essentially continguous memory, I think this is similar to your requirements.

Some sugar to do this in this lib would be nice though :)

**Comment by retep998** [comment]
This is not going to happen on Windows. To quote [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366763):

>No other memory allocation can take place in the region that is used for mapping, including the use of the VirtualAlloc or VirtualAllocEx function to reserve memory.

**Comment by danburkert** [comment]
The only thing I think we can really do here is expose MAP_FIXED, which is already being tracked in #21 , so I'm going to go ahead and close this.
