### ISSUE TITLE
Separate virtual page allocation from memory maps backed by page file

### ISSUE THREAD

**Issue by retep998** [danburkert/memmap-rs#31]
On linux both of these are done using `mmap` but on Windows these are very different. Memory maps are done using `CreateFileMappingW` and can be done either from an actual file or the page file, while virtual page allocation is done using `VirtualAlloc` which is significantly more flexible. The only reason you'd have to use a memory map backed by the page file on Windows however is because it is an NT object technically and can thus be shared with other processes making it useful for IPC.

**Comment by danburkert** [comment]
This is something I'd like to land before 1.0.  @retep998 do you have any interest in spiking this out?

**Comment by siriux** [comment]
Would this allow to reserve a range of addresses without reserving memory for it, and later commit small chunks in this space?

For this use case, I think that on linux we will need to use MAP_NORESERVE in anonymous mmaps to emulate the behavior of VirtualAlloc. But what about macosx support, is this even possible?

Thanks

**Comment by danburkert** [comment]
From IRC conversations with @retep998, it seems like this would best be done in another crate.  `memmap` will continue providing a thin wrapper around anonymous `mmap` and the closest equivalent in the Windows API, but nothing beyond that.
