### ISSUE TITLE
Add examples to methods

### ISSUE THREAD

**Issue by sfackler** [danburkert/memmap-rs#34]
See https://github.com/brson/rust-api-guidelines#c-example for details.

Note that this should be sequenced after #33.

**Comment by omh1280** [comment]
#45 Should do the trick. Let me know how it looks

Ottavio

**Comment by brson** [comment]
Thanks a bunch @omh1280 !

**Comment by brson** [comment]
@danburkert this can be closed.

**Comment by danburkert** [comment]
I've not closed this yet because there are still major refactors waiting to land (notably #46 and #31).

**Comment by xrl** [comment]
@danburkert I think this can be closed now because those two issues are closed.
