### ISSUE TITLE
File ownership

### ISSUE THREAD

**Issue by Lapin0t** [danburkert/memmap-rs#49]
It seems to me that the intended semantic in [`unix::MmapInner::open`](https://github.com/danburkert/memmap-rs/blob/master/src/unix.rs#L63) would be `file.into_raw_fd()` instead of `file.as_raw_fd()`. I'm not sure how `mmap` behaves in practice if the file descriptor is pointing to a closed file (if it was maped when open), but it seems like good abstraction to move the ownership of the file when mapping it.

Note that this would imply the following changes to `unix::MmapInner`:

- adding a field keeping track of the file descriptor
- changing the signature of `open(file: &File, ...)` to `open(file: File, ...)` (would also need to propagate to the user facing signatures)
- closing the file in the `Drop` implementation, after unmaping the memory

**Comment by danburkert** [comment]
>  I'm not sure how mmap behaves in practice if the file descriptor is pointing to a closed file

This is a crucial point.  The mapping will continue to work after the file descriptor is closed; there's no need to take ownership of the file descriptor.  Incidentally this isn't the case on Windows, but the Windows implementation works around that by duplicating the file descriptor (essentially what you've suggested the Unix implementation should do).  If the API were changed to take the file by value it would force users on Unix to duplicate or rename the file, which is an inconvenient and unnecessary overhead.

**Comment by danburkert** [comment]
@Lapin0t there is no such safe API when working with memory mapped files, so I don't think it's worth the trouble it would cause applications which do want to use the file and memory map in parallel (there are instances where this is safe to do).
