### ISSUE TITLE
Build error with rust 1.21

### ISSUE THREAD

**Issue by eclipseo** [danburkert/memmap-rs#54]
Works on 1.20, fails on 1.21 with the following error:
```
     Running `/usr/bin/rustc --crate-name cat examples/cat.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=e6f5be159863a10d -C extra-filename=-e6f5be159863a10d --out-dir /builddir/build/BUILD/memmap-0.5.2/target/release/examples -L dependency=/builddir/build/BUILD/memmap-0.5.2/target/release/deps --extern tempdir=/builddir/build/BUILD/memmap-0.5.2/target/release/deps/libtempdir-6b2c81b785a9b5c4.rlib --extern libc=/builddir/build/BUILD/memmap-0.5.2/target/release/deps/liblibc-32609fb12466c024.rlib --extern memmap=/builddir/build/BUILD/memmap-0.5.2/target/release/deps/libmemmap-f8b77f32bb5386b7.rlib -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now`
error: variable does not need to be mutable
   --> src/lib.rs:880:17
    |
880 |             let mut jitmem = unsafe { map.as_mut_slice() };
    |                 ^^^^^^^^^^
    |
note: lint level defined here
   --> src/lib.rs:3:9
    |
3   | #![deny(warnings)]
    |         ^^^^^^^^
    = note: #[deny(unused_mut)] implied by #[deny(warnings)]

error: aborting due to previous error

error: Could not compile `memmap`.
```

**Comment by KodrAus** [comment]
Thanks for the report @eclipseo! This should a nice quick fix, would you like to submit a PR for it?

**Comment by eclipseo** [comment]
Hum, I'm no Rust developer, just a package maintainer.

Furthermore it seems the culprit has been removed from the code already: https://github.com/danburkert/memmap-rs/commit/da7000b09478d1e94c66ba647a12450be93fa159#diff-b4aea3e418ccdb71239b96952d9cddb6L484

Maybe this is already fixed then and it just need a new release.

**Comment by KodrAus** [comment]
Hi sorry, I just got a chance to loop back to this. Since this is just a test, if it's not blocking you @eclipseo then maybe we can just wait until the next breaking release of `memmap` is released. Would that work for you, or do you need this fixed up and a patch pushed out?

**Comment by eclipseo** [comment]
It's not blocking me, I can wait.

**Comment by danburkert** [comment]
0.6.0 has been released with the `#[deny(warnings)]` attribute removed, so this shouldn't be an issue going forward.
