### ISSUE TITLE
How to access char devices?

### ISSUE THREAD

**Issue by victorcrimea** [danburkert/memmap-rs#59]
I a have a need to acce physical memory on arm device. I want to use memap to open /dev/mem but it fails with panic 
```
thread 'main' panicked at 'failed to map the file: Error { repr: Custom(Custom { kind: InvalidInput, error: StringErro
r("memory map must have a non-zero length") }) }', /checkout/src/libcore/result.rs:906:4
```
It looks like /dev/mem has zero length for memmap. How can I handle that situation?

**Comment by BurntSushi** [comment]
The man page for `mmap` says that `mmap` shall be supported for regular files, shared memory objects and typed memory objects. Support for any other type of file is unspecified.

Does `/dev/mem` fall into any of those three categories? It certainly doesn't seem to be a regular file.

**Comment by victorcrimea** [comment]
Here is an example of usage mmap on /dev/mem: [http://nairobi-embedded.org/mmap_n_devmem.html#system-ram-access](http://nairobi-embedded.org/mmap_n_devmem.html#system-ram-access)
It seems to be very common approach to manupulate physical memory through the mmaping.

**Comment by victorcrimea** [comment]
Don't you think that this fix is excess in unix.rs?
```
if aligned_len == 0 {
            // Normally the OS would catch this, but it segfaults under QEMU.
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "memory map must have a non-zero length",
            ));
        }
```

**Comment by victorcrimea** [comment]
Found solution.
For char devices programmer need to explicitly set length before mapping.
```rust
let mut mmap = unsafe {
	MmapOptions::new()
		.len(4096)
		.offset(0)
		.map_mut(&file).expect("failed to map the file") 
};
```
