### ISSUE TITLE
Empty Files not working

### ISSUE THREAD

**Issue by PSeitz** [danburkert/memmap-rs#64]
Hi, there seems to be an issue when, a Mmap is created and on an empty file.
I get an "The volume for a file has been externally altered so that the opened file is no longer valid." error under windows.

You can add this to the tests to reproduce. 
I also noticed the offset test is not working on Windows.
```
use std::fs::File;
#[test]
fn map_empty_file_copy() {
    let tempdir = tempdir::TempDir::new("mmap").unwrap();
    let path = tempdir.path().join("mmap");

    let file = OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .open(&path)
        .unwrap();

    let get_mmap = |file:&File| -> Mmap {
        unsafe { Mmap::map(&file).unwrap() }
    };

    let mmap = get_mmap(&file);
}

```

**Comment by BurntSushi** [comment]
I don't think you can memory map an empty file.

**Comment by PSeitz** [comment]
I see, there is already a test for this. Is there a way to append to a file via mmap?
