### ISSUE TITLE
Allow mapping memory safely using `volatile` crate?

### ISSUE THREAD

**Issue by goose121** [danburkert/memmap-rs#76]
It seems to me, reading through your justification for making file-backed memory maps unsafe, that the main reason for doing this is that they could change underneath you and thus violate Rust's memory model. However, a solution to this problem exists in the form of the [`volatile` crate](https://crates.io/crates/volatile)'s [`Volatile<T>` wrapper](https://docs.rs/volatile/0.2.4/volatile/struct.Volatile.html), which provides a safe way to read and write memory addresses which could change (with the added bonus that reads and writes are guaranteed not to be optimized away). It would still be beneficial to keep the existing unsafe interface in service, because the implementation of the `volatile` crate requires that data be copied whenever it is read, which may introduce an unacceptable amount of overhead for some users, but using it would provide other users the option of a safe interface.

Using the crate would just require the creation of `SafeMmap` and `SafeMmapMut` types, identical to their unsafe counterparts except that their `Deref` targets were `[Volatile<u8>]` rather than `[u8]`.

**Comment by goose121** [comment]
I agree that reading and writing entire records would still require further mechanisms to ensure integrity, but using `[Volatile<u8>]` means that the data changing while you have a reference to it does not cause undefined behaviour, allowing the data to be accessed safely. Any transformation from a subslice of the `[Volatile<u8>]` into a different type where the data having changed partway through reading the subslice could cause UB would require the client to write or invoke further unsafe code, in which case either the client or that unsafe code would be responsible for ensuring that the data was valid.

Furthermore, they couldn't do something like turning it from a `[u8]` into a string slice via a safe method, and then having the data change while the string slice referred to it, because the data would have to be copied out of the `Volatile` wrapper when it was read into a `[u8]`, at which point changes to the mapped data would have no effect on the string slice created

**Comment by burdges** [comment]
There is a [consensus against volatile](https://users.rust-lang.org/t/how-unsafe-is-mmap/19635/34) with remaining options being `&[AtomicU8]` with relaxed ordering, or maybe `*mut u8`, `&[UnsafeCell<u8>]`, `&[Cell<u8>]`, or an opaque type with buffer copy methods.  Quotes: 

"That said, I cannot think of any reason to actually use volatile here, or even think of any case where adding volatile removes UB. Adding volatile helps control the exact accesses that hit the memory subsystem, but I do not think it is ever needed from a UB perspective. So, to the best of my knowledge, `&[AtomicU8]` (and making every single access Relaxed) is okay. It is also rather horrible to use, I assume."

"relaxed atomic load/stores are the same as regular load/stores at an assembly level .. [and more optimizable] compared to volatile load/stores"

Relaxed `&[AtomicU8]` gives us [`fence`](https://doc.rust-lang.org/std/sync/atomic/fn.fence.html) which prevents the compiler or CPU from optimizing away simple protections like double accesses.  In fact checksums, or MAC tags, work without atomics, and provide stronger assurances, but many applications do not require such strong assurances.

**Comment by boomshroom** [comment]
I'm looking at code for a userspace device driver that `mmap`s in a device file and writes to it. The reason `volatile` is needed is because the compiler can't see that the writes are actually being read somewhere. That's the whole reason `volatile` exists: to allow optimised programs to use memory-mapped I/O. My first encounter with `Volatile` was writing to the x86 frame buffer. It's not thread safety that's needed (probably), but simply to ability to prevent writes from being erased.
