### ISSUE TITLE
Use with DirectIO

### ISSUE THREAD

**Issue by FallingSnow** [danburkert/memmap-rs#78]
Currently I'm using a mmap to modify a file opened with a `O_DIRECT` flag. This is so that I can write to the device in increments of the device's block size. However as I write more and more to the mmap it grows in memory. I'm not concerned about reading from the file/mmap, only writing. I only need to keep the last few bytes (to the lower block size bound) and what I am writing in the mmap.

For example, take this file on a device with a block size of 512 bytes.
```
|----------|----------|----------|------EOF
0         512       1024       1536
```
In this case I would want to the mmap offset to be 1536. Then I can write some data (24 bytes) to it, pad it 488 bytes of 0's and flush the 512 byte mmap. I suppose I would use `std::fs::File::set_len` to update the filesystem with the file's real length on every flush.

My question is is there a way to continuously truncate the start of the mmap, so it doesn't just keep growing and consuming memory as I write to it? Is [mremap](https://linux.die.net/man/2/mremap) a good use for this and does memmap-rs provide any built in methods for this?

P.S. I'm new to using mmap and direct io so if I'm doing anything completely wrong, I apologize.

**Comment by danburkert** [comment]
This isn't really the right place to ask this question.  The goal of `memmap` is to a high(ish) level wrapper to shared functionality of cross-platform memory maps.  Direct file IO and other platform specific exotica aren't in scope, and even if they were I think you'd be better off consulting your OS manual or asking in a platform-specific forum.

**Comment by FallingSnow** [comment]
I'm sorry. My question doesn't revolve around DirectIO, rather just providing my specific use case for slicing off/forgetting the beginning of a mmap. I was just wondering if there was a method of resizing the mmap and moving its index forward, and if not if that was on the roadmap?
