### ISSUE TITLE
Support `Mmap` on platforms without real mmap support

### ISSUE THREAD

**Issue by bjorn3** [danburkert/memmap-rs#88]
It could just read a file to `Vec<u8>` and then deref it to `&[u8]` on dereferencing `Mmap`. This would make it easier to port programs using an immutable mmap for efficiency reasons to platforms without mmap support, like WebAssembly.

cc https://github.com/rust-lang/miri/issues/722

**Comment by dekellum** [comment]
Hmm, could your/WASM code be made generic over `Deref<Target = [u8]>` (which includes `Mmap` and `Vec<u8>`)?  As an example, I do that in a wrapper type here: [`olio::mem::MemHandle`](https://docs.rs/olio/1.1.0/olio/mem/struct.MemHandle.html).

**Comment by bjorn3** [comment]
That would probably be uglier than just using `#[cfg(...)]` to replace `Mmap` with `Vec<u8>` on WASM. If you prefer to not make `Mmap` be backend by `Vec<u8>` on platforms supporting mmap, I will use `#[cfg(...)]`. This is mainly to make it easier for others.

**Comment by RReverser** [comment]
> This would make it easier to port programs using an immutable mmap for efficiency reasons to platforms without mmap support, like WebAssembly.

It would work only for immutable mmap though, right?

**Comment by RReverser** [comment]
This sounds pretty reasonable to me, especially if using `MmapMut` on such platforms still remains a compilation error.

**Comment by bjorn3** [comment]
+1 I guess I will add a new crate to rustc to abstract the switch between `Mmap` and `Vec<u8>` away from all places `Mmap` is used.
