### ISSUE TITLE
Error when mapping large files on Windows

### ISSUE THREAD

**Issue by Skielex** [danburkert/memmap-rs#91]
When I try to map files 2.1 GB or larger on Windows 10 I get errors.

Code looks like this:
``` rust
extern crate memmap;

use memmap::MmapOptions;
use std::fs::File;
use std::io::{self, Error, Write};

fn main() -> Result<(), Error> {

    let path = "<large file>";

    let file = File::open(path)?;
    let mmap = unsafe { MmapOptions::new().map(&file)? };

    io::stdout().write_all(&mmap[..10])?;

    Ok(())
}
```
- With a 2.1 GB file I get ```Error: Os { code: 8, kind: Other, message: "Not enough memory resources are available to process this command." }```.
- With a 16.6 GB file I get ```Error: Custom { kind: InvalidData, error: "memory map length overflows usize" }```
- Works file with a 1.1 GB file.

My machine has 32 GB memory and opening the files as memory maps in e.g. Python works just fine. I'm new to Rust, so perhaps I'm missing something obvious...

**Comment by KodrAus** [comment]
Hi @Skielex :wave:

Hmm, I'm wondering if you're ending up targeting 32bit instead of 64bit? What do you see if you add a:

```rust
println!("usize is: {}b", std::mem::size_of::<usize>());
```

and the output of:

```shell
rustup toolchain list
```

**Comment by Skielex** [comment]
Thanks for the reply, sorry for the late answer.
```usize is: 4b```
and
```stable-i686-pc-windows-msvc (default)```

So you're absolutely right. I thought it would target 64bit as default and also that 2.1 GB file should work for 32bit. I guess not... Thanks!
