### ISSUE TITLE
Handling IO-Errors during operation (which happen with network shares and connection drops)

### ISSUE THREAD

**Issue by Trolldemorted** [danburkert/memmap-rs#93]
Reading IO accesses can fail if you are working with a file on a network drive.

Could we get an API that enables us to handle those errors gracefully?

**Comment by BurntSushi** [comment]
AFAIK, such errors are only reported via OS signals. And reading I/O can fail in more mundane circumstances than reading off a network. For example, if a memory mapped file is truncated, then on Linux at least, you'll get a bus error via SIGBUS.

So I don't really see what kind of API that could be offered. It feels out of scope. But it would be easier to respond if you proposed the API you're looking for.

**Comment by Trolldemorted** [comment]
I don't know the APIs on linux/macos, but on windows a [try/catch pattern is recommended](https://docs.microsoft.com/en-us/windows/win32/memory/reading-and-writing-from-a-file-view):

```c
  DWORD dwLength;

  __try
  {
    dwLength = *((LPDWORD) lpMapAddress);
  }
  __except(GetExceptionCode()==EXCEPTION_IN_PAGE_ERROR ?
    EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    // Failed to read from the view.
  }
```

I assumed one could do something like this:
```rust
struct FileView {
    
}

impl FileView {
    unsafe fn try_read(&self, handle: &dyn Fn(&[u8]) -> ()) {
        // do the try-catch magic and call handle
        unimplemented!();
    }
}

fn main() {
    let fv = FileView {};
    unsafe { fv.try_read(&|slice| println!("{:?}", &slice[0..4])); }
}
```
Every access into the file view would be inside the trycatch (enforced by the borrow checker :tada:), and the "do all access inside a closure"-api is hopefully not too cumbersome to use. Unfortunately I have to admit I don't know if/how you can do c++'s try/catch stuff in rust.

**Comment by BurntSushi** [comment]
As far as I can tell, Rust has no way to do structured exception handling on Windows right now: https://github.com/rust-lang/rust/issues/38963

Separately, this is a deeply platform specific approach, and I don't think there is any rough equivalent on Unix. Unix uses signal handlers to report these kinds of errors. It's not clear to me that there exists a useful cross platform API to cover all of these things. For that reason, resolving your use case doesn't seem like a good fit for `memmap`.
