### ISSUE TITLE
❌  mmap.binary_search EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by sollyu** [danburkert/memmap-rs#96]
|name|value|
|-----|------|
|mac |10.15.6|
|rustc|1.47.0|
|memmap|0.7.0|

```rust
use std::ops::DerefMut;
use std::io::Write;

fn main() {
    let mmap_file_size: usize = 4 * 1024;
    let os_page_size: usize = unsafe { libc::sysconf(libc::_SC_PAGESIZE) as usize };
    let os_page_ratio: usize = mmap_file_size / os_page_size + 1;
    let mmap_memory_size: usize = os_page_size * os_page_ratio;

    let mmap_file: std::fs::File = std::fs::OpenOptions::new().read(true).write(true).create(true).open("test.mmap").unwrap();
    mmap_file.set_len(mmap_file_size as u64).unwrap();

    let mut mmap: memmap::MmapMut = unsafe { memmap::MmapOptions::new().len(mmap_memory_size).map_mut(&mmap_file).unwrap() };
    mmap.deref_mut().write(&[0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0xFF]).unwrap();
    mmap.flush().unwrap();

    let s:usize = mmap.binary_search(&0xff).unwrap();   // ❌ EXC_BAD_ACCESS (code=10, address=0x10d4ba000)
    println!("test={}", s);
}
```
我不知道为什么，谁能帮我一下，万分感谢，🙏
I don't know why. Who can help me? Thank you very much! 🙏

**Comment by pftbest** [comment]
Your mmap_file_size=4K but mmap_memory_size=8K. Make them the same. Also you wrote only 16 bytes to the memory, but you try to binary search over the whole page so this will also fail.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=15bd60a32e8ccb470fc775b577dff77e

**Comment by sollyu** [comment]
谢谢@pftbest 我想寻找mmap文件的末尾标志。就像这样：
Thank you @pftbest  I'm looking for the end of the MMAP file. Like this:

![image](https://user-images.githubusercontent.com/43105186/98345056-19114700-204f-11eb-8127-cf5e4b62272c.png)

这个标志可能在4k文件的任意位置，这样的功能，我需要怎么做？
This flag may be anywhere in 4K file. What do I need to do with this function?
